### ISSUE TITLE
Why return namespaced keywords only?

### ISSUE THREAD

**Issue by efraimmgon** [walkable-server/walkable#111]
(Note: I've never worked with Om, Om-next or Pathom. I’ve read Walkable’s docs and it does not contain (as far as I can see) an answer. )

Is this a feature of Pathom or a design choice of Walkable? In either case, why is it so?

Is there a way to get unnamespaced keys? If not, why?

Having worked with clojure.java.jdbc, reagent, and friends I cannot understand the reason for this. I can only see the extra time it will take to type the namespaced keys every time I want to get a field.

Perhaps adding/linking some of the reasonings on the README/docs will help new users wrap their heads around some of the choices.

To end on a positive note, the library is great! Clojure was in dire need of something like this. 

Keep up the good work!

**Comment by myguidingstar** [comment]
By using namespaced keywords, Walkable's engine doesn't have to keep track of current table when it travels the graph, therefore the code is a little bit simpler.

I think the way Pathom works also encourages this approach.
There's no way to get unnamespaced keywords. You must provide namespaced keywords in your queries, and the results are in namespaced keywords, too.
I feel namespace keywords have become something natural since their introduction to Clojure ecosystem. I even think forcing people to use namespaced keywords is a good thing :)

**Comment by efraimmgon** [comment]
Yeah man, after watching a [talk](https://www.youtube.com/watch?v=r3zywlNflJI) from Pathom's creator, and using Walkable for a couple of days, I'm 90% convinced this is the way to go.

The talk link is on Pathom's github page, but perhaps it would be useful to have such a resource (or something similar) on Walkable's README too. Seeing the lib used helps a lot to understand the power the it provides.

I, for one, am surprised I haven't heard of Pathom or Walkable before.
