### ISSUE TITLE
Readme fixes

### ISSUE THREAD

**Issue by efraimmgon** [walkable-server/walkable#117]
The new docs are nice. 

One thing I'd improve add is syntax highlighting, since it's difficult to distinguish the comments from the configuration.

The [link to the floor-plan docs](https://github.com/walkable-server/walkable-server.github.io/tree/ee970dafd13b3f6a6f6b8fa3001e171b44b85f26/doc/floor-plan.md) is broken (at https://walkable.gitbook.io/walkable/). It should be https://walkable.gitbook.io/walkable/doc/floor-plan.

At the same page, the link to [dev.cljs](https://github.com/walkable-server/walkable/tree/ab05c4706867ea7cce2daa6b903ee23834e1cf7f/dev/src/dev.cljs) is broken. It should be https://github.com/walkable-server/walkable/blob/master/dev/src/common/dev.cljs.

**Comment by efraimmgon** [comment]
[](https://github.com/walkable-server/walkable-server.github.io/pull/1)

**Comment by myguidingstar** [comment]
This is not your fault at all but gitbook seems to break if modifications is made directly from git. (So far I only made it in `gitbook.io`'s web ui). I'm talking about the section "Who should use Walkable?"

Syntax highlighting doesn't work as expected, either.

Maybe we should set up gitbook build with travis-ci instead of relying on `gitbook.io`.

The Overview section is still a mess. I'm figuring out how to restructure it.

**Comment by myguidingstar** [comment]
Documentation is currently living in https://walkable.gitlab.io
Still a work in progress

**Comment by efraimmgon** [comment]
Nice!

**Comment by myguidingstar** [comment]
all pages should look ok now. Overview and Installation still need some love...
