### ISSUE TITLE
Bug on joins with null foreign-key

### ISSUE THREAD

**Issue by efraimmgon** [walkable-server/walkable#158]
** [EDIT] In the next comments I have identified the issue.

I have a location and a neighborhood table, with the following floor-plan:

```clojure
{:idents {:locations/all "location"
          :neighborhood/by-id :neighborhood/id}
 :join [:location/neighborhood [:location/neighborhood-id :neighborhood/id]]}
```

When I query

```clojure
[{[:locations/all] [{:location/neighborhood [:neighborhood/id]}]}]
```

I get the following sql output

```sql
[SELECT ("location"."neighborhood_id") AS "location/neighborhood-id" FROM "location"]
[SELECT * FROM (SELECT ("neighborhood"."id") AS "neighborhood/id" FROM "neighborhood" WHERE (("neighborhood"."id")=(1)))
 UNION ALL
 SELECT * FROM (SELECT ("neighborhood"."id") AS "neighborhood/id" FROM "neighborhood" WHERE (("neighborhood"."id")=()))]
```

and the error `Error: near ")": syntax error`.

You can notice that on the last `select` the neighborhood.id is not given.

Oddly enough, if I change the query to the following (where I query by id, instead of querying all rows) there's no error:

```clojure
[{[:location/by-id 1] [{:location/neighborhood [:neighborhood/id]}]}]
--> {[:location/by-id 1] {:location/neighborhood [{:neighborhood/id 1}]}}
```

I have read the docs and as far as I can tell my floor-plan seems correct.

**Comment by efraimmgon** [comment]
After a bit more of digging It seems the reason `locations/all`query does not work is because one of the values for location.neighborhood_id (foreign key) is null.

I guess the solution would be to filter the rows where the location.neighborhood_id is not nil, but what is the equivalent in walkable since the following seems to be invalid?

```clojure
[{(:locations/all
   {:filters [:is-not :location/neighborhood-id nil]}) 
  [:location/neighborhood-id]}]
```

**Comment by efraimmgon** [comment]
Indeed, checking the source there's no implementation for `:is` or `:is-not` in `walkable.sql-query-builder.expressions`. It doesn't seem to hard to implement them, but wouldn't it make sense to have them by default?

**Comment by efraimmgon** [comment]
As to the original problem, I think it is a bug and one should not have to filter out the nil foreign keys, simply because you don't have to do it when writing the query in plain sql. Of course I have no idea how hard it would be to implement that.

**Comment by myguidingstar** [comment]
Thanks for reporting the issue and the great analysis.
IIRC, SQL `is` operator has only one use case which is to check with `null`, so I'd prefer a Clojure-ish operator `nil?` that generates sql string `is null`. Combine it with `:not` like this `[:not [:nil? :foo/bar]]`.

You can implement such `nil?` operator in walkable by modifying the macro`walkable.sql-query-builder.expressions/import-functions` so that it can produce "postfix" functions when arity number is 1, something like:
```clj
(import-functions {:arity 1 :postfix true}
  {nil? " is null"})
```
Places to look at: 
https://github.com/walkable-server/walkable/blob/a8fc4bb7f7e6af8b6d7b60c28df3458d5890674a/src/walkable/sql_query_builder/expressions.cljc#L285
https://github.com/walkable-server/walkable/blob/a8fc4bb7f7e6af8b6d7b60c28df3458d5890674a/src/walkable/sql_query_builder/expressions.cljc#L302
https://github.com/walkable-server/walkable/blob/a8fc4bb7f7e6af8b6d7b60c28df3458d5890674a/src/walkable/sql_query_builder/expressions.cljc#L322

**Comment by myguidingstar** [comment]
Currently, after fetching rows from database, walkable just use whatever value from the column to create with the `=` operator to create the filter, something like `[:= 'source-column 'target-column]`
https://github.com/walkable-server/walkable/blob/a8fc4bb7f7e6af8b6d7b60c28df3458d5890674a/src/walkable/sql_query_builder/floor_plan.cljc#L453
https://github.com/walkable-server/walkable/blob/a8fc4bb7f7e6af8b6d7b60c28df3458d5890674a/src/walkable/sql_query_builder/floor_plan.cljc#L468
Ideally, source column should be checked with `nil?` first before checking for equality, something like:
```
[:and [:not [:nil? 'source-column]]
      [:= 'source-column 'target-column]]
```
Source-column and target-column are walkable's internal variables.

**Comment by myguidingstar** [comment]
@efraimmgon can you check if the branch `non-int-join` fixes the problem?

**Comment by efraimmgon** [comment]
How do I do that? I'm a git noob, sorry.

**Comment by myguidingstar** [comment]
@efraimmgon the latest snapshot should work now
